import json
import os
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import parse_qs, urlparse


BASE_DIR = Path(__file__).resolve().parent
ASSET_DIR = BASE_DIR / "static" / "assets"
CSS_PATH = BASE_DIR / "static" / "css" / "style.css"

IMAGES = {
    "silent-lake": {
        "title": "Silent Lake",
        "thumb": "lake_thumb.png",
        "original": "lake_original.png",
        "note": "Archived by the CDN migration job.",
    },
    "server-room": {
        "title": "Server Room",
        "thumb": "server_thumb.png",
        "original": "server_thumb.png",
        "note": "No original copy retained.",
    },
}


def html_page(title, body):
    return f"""<!doctype html>
<html lang="vi">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{title}</title>
    <link rel="stylesheet" href="/static/css/style.css">
  </head>
  <body>{body}</body>
</html>
"""


def index_html():
    tiles = []
    for image_id, image in IMAGES.items():
        tiles.append(
            f"""<a class="tile" href="/image/{image_id}">
          <img src="/static-view/{image_id}" alt="{image['title']}">
          <div>
            <h2>{image['title']}</h2>
            <p>{image['note']}</p>
          </div>
        </a>"""
        )
    body = f"""<main class="shell">
      <section class="topbar">
        <div>
          <p class="eyebrow">Internal Evidence Gallery</p>
          <h1>Metadata Gallery</h1>
        </div>
        <span class="status">CDN mirror online</span>
      </section>
      <section class="grid">{''.join(tiles)}</section>
    </main>"""
    return html_page("Metadata Gallery", body)


def image_html(image_id, image):
    body = f"""<main class="shell">
      <nav class="nav"><a href="/">Back</a></nav>
      <section class="viewer">
        <img src="/static-view/{image_id}" alt="{image['title']}">
        <div class="meta">
          <p class="eyebrow">Evidence item</p>
          <h1>{image['title']}</h1>
          <p>{image['note']}</p>
          <p class="muted">Preview generated by CDN sanitizer. Original object lookup is handled by the archive worker.</p>
        </div>
      </section>
    </main>"""
    return html_page(f"{image['title']} - Metadata Gallery", body)


class Handler(BaseHTTPRequestHandler):
    server_version = "MetadataGallery/1.0"

    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path

        if path == "/":
            return self.send_text(index_html(), "text/html; charset=utf-8")
        if path == "/robots.txt":
            body = "User-agent: *\nDisallow: /archive/\nDisallow: /debug/\nSitemap: /sitemap.xml\n"
            return self.send_text(body, "text/plain; charset=utf-8")
        if path == "/sitemap.xml":
            body = """<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>/image/silent-lake</loc></url>
  <url><loc>/image/server-room</loc></url>
</urlset>
"""
            return self.send_text(body, "application/xml; charset=utf-8")
        if path == "/healthz":
            return self.send_text(json.dumps({"ok": True}), "application/json")
        if path == "/static/css/style.css":
            return self.send_file(CSS_PATH, "text/css; charset=utf-8")
        if path.startswith("/image/"):
            image_id = path.rsplit("/", 1)[-1]
            image = IMAGES.get(image_id)
            if not image:
                return self.not_found()
            return self.send_text(image_html(image_id, image), "text/html; charset=utf-8")
        if path.startswith("/static-view/"):
            image_id = path.rsplit("/", 1)[-1]
            image = IMAGES.get(image_id)
            if not image:
                return self.not_found()
            headers = {
                "X-CDN-Cache": "HIT",
                "X-Archive-Key": image_id,
            }
            if image_id == "silent-lake":
                headers["X-Origin-Path"] = "/archive/original?id=silent-lake"
            return self.send_file(ASSET_DIR / image["thumb"], "image/png", headers)
        if path == "/archive/original":
            image_id = parse_qs(parsed.query).get("id", [""])[0]
            image = IMAGES.get(image_id)
            if not image:
                return self.not_found()
            if image_id != "silent-lake":
                return self.send_text("forbidden\n", "text/plain", HTTPStatus.FORBIDDEN)
            headers = {
                "Content-Disposition": 'attachment; filename="lake_original.png"',
                "X-Content-Note": "original file, metadata preserved",
            }
            return self.send_file(ASSET_DIR / image["original"], "image/png", headers)

        return self.not_found()

    def send_text(self, body, content_type, status=HTTPStatus.OK):
        data = body.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def send_file(self, path, content_type, extra_headers=None):
        if not path.is_file():
            return self.not_found()
        data = path.read_bytes()
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(data)))
        for key, value in (extra_headers or {}).items():
            self.send_header(key, value)
        self.end_headers()
        self.wfile.write(data)

    def not_found(self):
        self.send_text("not found\n", "text/plain; charset=utf-8", HTTPStatus.NOT_FOUND)

    def log_message(self, fmt, *args):
        print(f"{self.client_address[0]} - {fmt % args}")


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "8080"))
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    print(f"Metadata Gallery listening on 0.0.0.0:{port}")
    server.serve_forever()
